#
# Generated by ros2recipe.py
#
# Copyright openeuler

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "TODO: Package description"
AUTHOR = "root"
SECTION = "devel"
LICENSE = "CLOSED"
LIC_FILES_CHKSUM = "file://package.xml;beginline=8;endline=8;md5=782925c2d55d09052e1842a0b4886802"

ROS_CN = ""
PV = "0.0.0"
ROS_BPN = "test-send"

ROS_BUILD_DEPENDS = " \
    hibot-user-driver \
    libhibot \
    rclcpp \
    shm-meta-info \
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = " \
    rclcpp \
    shm-meta-info \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    hibot-user-driver \
    libhibot \
    rclcpp \
    shm-meta-info \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

OPENEULER_LOCAL_NAME = "component_hibot"
SRC_URI = " \
    file://${OPENEULER_LOCAL_NAME}/sample/shm_demo/src/test_send \
    file://${OPENEULER_LOCAL_NAME}/sample/shm_demo/src/SHMBufferRosPkg \
    file://test_send_fix.patch \
"

# libhibot.so provides by libhibot, remove it here
do_install:append(){
    if [ -e ${D}${libdir}/libhibot.so ]; then
        rm -f ${D}${libdir}/libhibot.so
    fi
}

S = "${WORKDIR}/component_hibot/sample/shm_demo/src/test_send"
FILES:${PN} += "${datadir} ${libdir}/test_send/*"
DISABLE_OPENEULER_SOURCE_MAP = "1"
ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
