#!/bin/bash

# 8021q modules
insmod /lib/modules/5.10.0/kernel/net/llc/llc.ko
insmod /lib/modules/5.10.0/kernel/net/802/stp.ko
insmod /lib/modules/5.10.0/kernel/net/802/garp.ko
insmod /lib/modules/5.10.0/kernel/net/8021q/8021q.ko

