# main bbfile yocto-poky/meta/recipes-core/base-files/base-files_3.0.14.bb
# we create this file as a layer to use openeuler's configs files
# config files use openeuler's, see base-files under this dir

FILESEXTRAPATHS:prepend := "${THISDIR}/base-files/:"

SRC_URI += " \
    file://oelogo.txt \
    "

BANNERSTR = "Authorized uses only. All activity may be monitored and reported."

# The openEuler string logo lives in base-files/oelogo.txt as the single
# source, displayed once per session by the pre-login issue files. It is
# deliberately NOT repeated in /etc/motd:
#   /etc/issue.net     printed verbatim by sshd before login
#   /etc/issue.d/      agetty expands backslash sequences, so the art is
#                      double-escaped and mixed with dynamic escapes:
#                      \r kernel, \m arch, \l tty, \4 interface IP
#   /run/motd          runtime info only, generated by openeuler-motd
do_install_basefilesissue:append () {
    # drop-in displayed by agetty after /etc/issue
    install -d ${D}${sysconfdir}/issue.d
    {
        printf '%s\n' '\e{bold}\e{cyan}openEuler Embedded \r on \m\e{reset}'
        printf '%s\n' '\e{cyan}ip: \4  console: \l\e{reset}'
        printf '%s\n' '\e{lightblue}'
        sed 's/\\/\\\\/g' ${WORKDIR}/oelogo.txt
        printf '%s\n' '\e{reset}'
        echo "${BANNERSTR}"
        echo
    } > ${D}${sysconfdir}/issue.d/openeuler-logo.issue
    # displayed by sshd before login (no escape expansion); keep the
    # ${DISTRO_NAME}/${DISTRO_VERSION} line written by base-files itself
    cat ${WORKDIR}/oelogo.txt >> ${D}${sysconfdir}/issue.net
    echo >> ${D}${sysconfdir}/issue.net
    echo "${BANNERSTR}" >> ${D}${sysconfdir}/issue.net
    echo >> ${D}${sysconfdir}/issue.net
}

do_install:append () {
    # /etc/motd points to the dynamically generated /run/motd
    # (openeuler-motd), so sshd and login show fresh runtime system info
    # after login without repeating the pre-login logo
    rm ${D}${sysconfdir}/motd
    ln -s /run/motd ${D}${sysconfdir}/motd
}

ASSUME_PROVIDE_PKGS:${PN} = "setup filesystem basesystem"
