TOOLCHAIN = "clang"
DEPENDS:append = " clang-cross-${TARGET_ARCH}"
do_kernel_configme[depends] += "clang-cross-${TARGET_ARCH}:do_populate_sysroot"
DEPENDS:remove = "virtual/${TARGET_PREFIX}gcc"
KERNEL_CC = "${CCACHE}${HOST_PREFIX}clang ${HOST_CC_KERNEL_ARCH} ${DEBUG_PREFIX_MAP} -fdebug-prefix-map=${STAGING_KERNEL_DIR}=${KERNEL_SRC_PATH}"
