# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
from pathlib import Path

import sphinxcontrib.mermaid as sphinxcontrib_mermaid


def _skip_mermaid_js(*args, **kwargs):
    pass


# Load Mermaid from html_js_files only. This keeps Mermaid dependencies small
# and avoids extra d3/fullscreen scripts injected by sphinxcontrib-mermaid.
sphinxcontrib_mermaid.install_js = _skip_mermaid_js

DOC_BASE = Path(__file__).resolve().parents[1]

# -- Project information -----------------------------------------------------

project = 'openEuler Embedded在线文档'
copyright = '2026, openEuler Embedded'
author = 'openEuler Embedded'

# The full version, including alpha/beta/rc tags
release = '25.03'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx_multiversion',
              'sphinx_tabs.tabs',
              'sphinxcontrib.mermaid',
              "myst_parser",]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

myst_fence_as_directive = ["mermaid"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
html_sidebars = {
    '**': [
        'versions.html',
    ],
}

# 指定哪个分支为 latest 版本
smv_latest_version = 'master'

# Build published documentation only from upstream release branches.
smv_remote_whitelist = r'^upstream$'
smv_branch_whitelist = r'^(master|openEuler-[0-9]+\.[0-9]+(-LTS)?(-SP[0-9]+)?)$'
smv_tag_whitelist = r'^$'
smv_prefer_remote_refs = True


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.

# There is no need to configure the language, it will prevent us from searching Chinese. 
# language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = "sphinx_rtd_theme"
html_theme_options = {
    'navigation_depth': 7,
    'collapse_navigation': True,
    'sticky_navigation': False,
}

html_css_files = [
    'css/custom.css',
]

html_js_files = [
    'js/mermaid.min.js',
    'js/mermaid-run.js',
    'js/custom.js',
]

mermaid_output_format = 'raw'
mermaid_version = '11.12.1'
mermaid_include_elk = False
mermaid_fullscreen = False
mermaid_init_config = {
    'startOnLoad': False,
    'securityLevel': 'loose',
    'theme': 'default',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_favicon = str(DOC_BASE / "source" / "_static" / "images" / "favicon.ico")

master_doc= 'index'

html_show_sourcelink = False

latex_engine = "xelatex"

latex_elements = {
    'papersize': 'a4paper',
    'utf8extra': '',
    'inputenc': '',
    'cmappkg': '',
    'fontenc': '',
    'preamble': r'''
        \usepackage{xeCJK}
        \usepackage{indentfirst}
        \setlength{\parindent}{2em}
        \setCJKmainfont{Noto Sans CJK SC}
        \setCJKmonofont{Noto Sans Mono CJK SC}
        \XeTeXlinebreaklocale "zh"
        \XeTeXlinebreakskip = 0pt plus 1pt
    ''',
}

latex_documents = [
    (master_doc, 'openeuler.tex', 'openEuler Embedded使用与开发手册',
     '作者：openEuler Embedded', 'manual', True),
]
