[Unit]
After=systemd-tmpfiles-setup.service

[Service]
ExecStartPre=
ExecStartPre=/bin/grep -q control_d /proc/xen/capabilities
ExecStartPre=/bin/mkdir -p /var/volatile/log
ExecStartPre=/bin/mkdir -p ${XENCONSOLED_LOG_DIR} /run/xen
