FROM hub.oepkgs.net/openeuler/openeuler:24.03 AS builder

RUN yum -y install cpio wget

ARG BASE_URL=http://121.36.84.172/dailybuild/EBS-openEuler-Mainline/embedded_img/aarch64/3591rc-ibrobot-dev

RUN TIMESTAMP=$(curl -s ${BASE_URL}/ | grep -oP 'href="\K\d+(?=/")' | head -1) && \
    wget -c --tries=0 --timeout=30 -O /root/rootfs.cpio.gz "${BASE_URL}/${TIMESTAMP}/openeuler-image-3591rc-${TIMESTAMP}.rootfs.cpio.gz"

RUN cd /root && \
    mkdir -p openeuler_rootfs && \
    cd openeuler_rootfs && \
    gzip -dc /root/rootfs.cpio.gz | cpio -idm && \
    rm -f /root/rootfs.cpio.gz

FROM hub.oepkgs.net/openeuler/openeuler:24.03

RUN yum -y install qemu-user-static cpio

COPY --from=builder /root/openeuler_rootfs /root/openeuler_rootfs

RUN rm -f /root/openeuler_rootfs/etc/resolv.conf && \
    echo "nameserver 114.114.114.114" > /root/openeuler_rootfs/etc/resolv.conf && \
    echo "nameserver 223.5.5.5" >> /root/openeuler_rootfs/etc/resolv.conf

RUN echo 'if [ -d /root/openeuler_rootfs ] && [ "$$DO_CHROOT" != "1" ]; then' >> /root/.bashrc && \
    echo '    export DO_CHROOT=1' >> /root/.bashrc && \
    echo '    exec chroot /root/openeuler_rootfs /bin/bash' >> /root/.bashrc && \
    echo 'fi' >> /root/.bashrc

WORKDIR /root

ENTRYPOINT ["/bin/bash"]
CMD ["-l"]
