#! /bin/sh

case "$1" in
  start)
    echo "Starting resize2fs_once."
    ROOT_DEV=$(findmnt / -o source -n) &&
    resize2fs $ROOT_DEV &&
    rm /etc/init.d/resize2fs_once &&
    echo "done"
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 1
    ;;
esac
